#ifndef __IXSTAT_FUNC_API_INCLUDED
#define __IXSTAT_FUNC_API_INCLUDED

#define MAP_STAT_INFO_OPCODE_LEN		64

#define MAP_STAT_INFO_SRI				"SRI"
#define MAP_STAT_INFO_INFORM			"INFORM_SC"
#define	MAP_STAT_INFO_REPORT_SM			"REPORT_SM"
#define MAP_STAT_INFO_READY_FOR_SM		"READY_FOR_SM"
#define MAP_STAT_INFO_REQ				"REQ"
#define MAP_STAT_INFO_MOF				"MOF"
#define MAP_STAT_INFO_MTF				"MTF"
#define MAP_STAT_INFO_ALERT_SC			"ALERT_SC"
#define MAP_STAT_INFO_SMSC_MOF_RECV		"SMSC_MOF_RECV"
#define MAP_STAT_INFO_SMSC_MOF_SEND		"SMSC_MOF_SEND"

#define MAP_STAT_INFO_LIST_NORMAL		5
#define MAP_STAT_INFO_LIST_INFORM		2


/* API Prototype */
void StatProc(void *arg);

#endif
